# syntax=docker/dockerfile:1

FROM postgres:13

COPY blog-2021_06_29_17_44_37-dump.sql /docker-entrypoint-initdb.d/


## dump build stage
#FROM postgres:13 as dumper
#
#COPY blog-2021_06_29_17_44_37-dump.sql /docker-entrypoint-initdb.d/
#
#RUN ["sed", "-i", "s/exec \"$@\"/echo \"skipping...\"/", "/usr/local/bin/docker-entrypoint.sh"]
#
#ENV POSTGRES_USER=blog
#ENV POSTGRES_PASSWORD=blog
#ENV PGDATA=/data
#
#RUN ["/usr/local/bin/docker-entrypoint.sh", "blog"]
#
## final build stage
#FROM postgres:13
#
#COPY --from=dumper /data $PGDATA
