version: "3.8"

services:
  db:
#    image: "postgres:13"
    build:
      context: .
      dockerfile: Dockerfile_db
    ports:
      - "5431:5432"   # 5431, if 5432 is busy with you
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=blog
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: